### ISSUE TITLE
pytorch 和 torchvision 版本对应问题

### ISSUE THREAD

**Issue by superior1993** [svip-lab/impersonator#67]
您好,非常感谢你的工作,
我有一些疑问,按照你所提供的requirements.txt:在训练的时候pytorch版本是1.2.0,torchvivion0.4.0.但是评价指标测试是pytorch版本是1.2.0,torchvivion0.4.2.
如果这样运行,程序会出错,你是怎么解决的呢?查询torchvision0.4.2,配套的pytorch版本是高于1.2.0

谢谢

**Comment by StevenLiuWen** [comment]
@superior1993 ,您好，那个torchvision=0.4.2确实有一点不匹配torch 1.2.0，我当时可能是直接用pip管理工具直接导出的requirements.txt，没有注意到这个问题。你尝试一下安装torch 1.2.0和对应的torchvision=0.4.2
看一下这样是否可行。应该是没问题的，因为那个测试代码里面只用了torchvision里面的inception_v3这个模块。这个模块0.4.0和0.4.2应该是一样的。我之后改一下那个torchvision的版本。

**Comment by superior1993** [comment]
我将torchvision换成0.4.0,试了运行evaluate.sh,还是会报错的,报了如下两个错误,第二次错误是因为图片没有加载进来,应该是和第一次错误是关联的.你有遇过这样的问题的吗?
还有一个问题想要咨询一下,你在做评价指标的时候,是直接运行evaluate.sh,就可以测出指标了吗?
谢谢

![图片](https://user-images.githubusercontent.com/40931457/100880966-58b13e80-34e8-11eb-9395-9c763856fe12.png)
![图片](https://user-images.githubusercontent.com/40931457/100881045-7088c280-34e8-11eb-8587-fd1827701a30.png)

**Comment by StevenLiuWen** [comment]
@superior1993 , evaluate.sh里面的第三行和第四行的路径换了吗？https://github.com/svip-lab/impersonator/blob/master/scripts/motion_imitation/evaluate.sh#L3

data_dir="/p300/tpami/iPER"  # need to be replaced!!!!!
output_dir="/p300/iccv2019/baselines/LWG-ADD"  # need to be replaced!!!!!

**Comment by superior1993** [comment]
换了,换成本地路径了.但还是报错,因为我不想测太多指标,所以删减了一些指标,但是这个应该影响不大吧,
因为部分可以加载,但是部分不能加载,所以出错了.
![图片](https://user-images.githubusercontent.com/40931457/100883609-7af88b80-34eb-11eb-909f-7695c3b4f8a1.png)

另外你的代码中还有一处应该是数据集更新了吧,我下载的是之前的数据集,图片文件是images,但是代码中拼接路径是images_HD.

**Comment by StevenLiuWen** [comment]
images_HD是https://onedrive.live.com/?authkey=%21AJL%5FNAQMkdXGPlA&id=3705E349C336415F%2188052&cid=3705E349C336415F这里面的iPER_1024_video_release.zip里面的视频解压出来的图片。如果你之前是只有images的，你可以把测试那个protocol里面的images_HD换成images

**Comment by superior1993** [comment]
恩恩,好的谢谢.在测试评价指标的时候,json文件取src_image时候,图片名字有的是三位,有的是四位,比如0000.jpg,029.jpg,这个是你在分割图片是怎么设定的呢?

**Comment by superior1993** [comment]
恩恩,这个我之前调代码已经修改,并且重新修改图片名称,使其和json文件中,图片格式一致(0000.jpg),因为ools/unzip_iPER.py中生成的图片格式是frame00000000.png.我以为这样修改之后代码可以跑通,但还是报错图片没有加载成功.
![图片](https://user-images.githubusercontent.com/40931457/101020955-2ff17d80-35aa-11eb-927b-a36fb3f35f53.png)
![图片](https://user-images.githubusercontent.com/40931457/101020989-3e3f9980-35aa-11eb-81ec-08d82f144c27.png)

**Comment by StevenLiuWen** [comment]
你好，这个是我们之前处理标注[iPER_protocol.json](https://github.com/svip-lab/impersonator/blob/master/thirdparty/his_evaluators/data/iPER_protocol.json)和解压视频命名的时候[tools/unzip_iPER.py](https://github.com/svip-lab/impersonator/blob/master/tools/unzip_iPER.py#L29)不一致的问题导致的。
在iPER_protocol.json中，所有的名字是xxxxx.jpg, 这里的xxxxx是当前视频有帧的位数，例如1350帧，就是0000.jpg。
在unzip_iPER.py中，所有 的名字都是frame_00000000.png。

我们刚才修复了这个bug，你有clone一下最新的代码，[tools/unzip_iPER.py](https://github.com/svip-lab/impersonator/blob/master/tools/unzip_iPER.py#L29)，我们现在把他全部统一了。

**Comment by superior1993** [comment]
恩恩,好的,方便加你微信吗?我的微信号是zq11051217

**Comment by FrankMelon1** [comment]
你好，我在更换evaluate.sh的路径后，并且使用最新代码，在运行evaluate.sh时还是会遇到以下问题：

running ('ssim', 'psnr', 'lps', 'face-CS', 'OS-CS-reid') metrics with paired samples = 0
running ('OS-freid', 'face-FD', 'is', 'face-CS', 'OS-CS-reid', 'fid') metrics with unpaired samples = 0

我输出了中间all_si_preds_ref_file_list，all_ci_preds_ref_file_list都是空列表
请问这是什么原因呢？期待您的回复！

**Comment by StevenLiuWen** [comment]
你是运行我们的吗？可以截图发我一下log的错误，尽可能多一点。

发自我的iPhone

**Comment by FrankMelon1** [comment]
> 你是运行我们的吗？可以截图发我一下log的错误，尽可能多一点。 发自我的iPhone
> […](#)
> 在 2021年2月22日，下午6:10，FrankMelon1 ***@***.***> 写道： ﻿ 你好，我在更换evaluate.sh的路径后，并且使用最新代码，在运行evaluate.sh时还是会遇到以下问题： running ('ssim', 'psnr', 'lps', 'face-CS', 'OS-CS-reid') metrics with paired samples = 0 running ('OS-freid', 'face-FD', 'is', 'face-CS', 'OS-CS-reid', 'fid') metrics with unpaired samples = 0 我输出了中间all_si_preds_ref_file_list，all_ci_preds_ref_file_list都是空列表 请问这是什么原因呢？期待您的回复！ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

您好！是运行你们的，下面是全部报错信息，感谢您的回复：
------------ Options -------------
T_pose: False
batch_size: 4
bg_ks: 13
bg_model: ./outputs/checkpoints/deepfillv2/net_epoch_50_id_G.pth
bg_replace: False
body_seg: False
cam_strategy: smooth
checkpoints_dir: ./outputs/checkpoints/
cond_nc: 3
data_dir: /workspace/cpfs-data/data/iPER
dataset_mode: iPER
debug: False
do_saturate_mask: False
face_model: assets/pretrains/sphere20a_20171020.pth
front_warp: False
ft_ks: 3
gen_name: impersonator
gpu_ids: 0
has_detector: True
hmr_model: assets/pretrains/hmr_tf2pt.pth
image_size: 256
images_folder: images_HD
ip: 
is_train: False
load_epoch: 0
load_path: ./outputs/checkpoints/lwb_imper/net_epoch_30_id_G.pth
map_name: uv_seg
model: imitator
n_threads_test: 2
name: imper_results
norm_type: instance
only_vis: False
output_dir: /workspace/cpfs-data/impersonator-master/output_evaluate
part_info: assets/pretrains/smpl_part_info.json
port: 31100
post_tune: True
pri_path: ./assets/samples/A_priors/imgs
repeat_num: 6
save_res: False
serial_batches: False
smpl_model: assets/pretrains/smpl_model.pkl
smpls_folder: smpls
src_path: 
swap_part: body
test_ids_file: val.txt
tex_size: 3
tgt_path: 
time_step: 10
train_ids_file: train.txt
uv_mapping: assets/pretrains/mapper.txt
view_params: R=0,90,0/t=0,0,0
-------------- End ----------------
./outputs/checkpoints/imper_results
Network impersonator was created
Loading net: ./outputs/checkpoints/lwb_imper/net_epoch_30_id_G.pth
Network deepfillv2 was created
Loading net: ./outputs/checkpoints/deepfillv2/net_epoch_50_id_G.pth
  0%|                                                                                                 | 0/126 [00:00<?, ?it/s]
Setting up Perceptual loss...
Loading model from: /workspace/cpfs-data/impersonator-master/thirdparty/his_evaluators/his_evaluators/metrics/lpips/weights/v0.1/alex.pth
...Done
[OSNET info] Successfully loaded pretrained weights from "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/data/osnet_ibn_x1_0_imagenet.pth"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
running ('ssim', 'psnr', 'lps', 'face-CS', 'OS-CS-reid') metrics with paired samples = 0
0it [00:00, ?it/s]
/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)
ssim = nan, quality = higher score is better
psnr = nan, quality = higher score is better
lps = nan, quality = lower score is better.
face-CS = nan, quality = higher score is better
OS-CS-reid = nan, quality = higher score is better
running ('OS-freid', 'fid', 'face-CS', 'face-FD', 'is', 'OS-CS-reid') metrics with unpaired samples = 0
0it [00:00, ?it/s]
Traceback (most recent call last):
  File "evaluate.py", line 137, in <module>
    device=torch.device("cuda:0")
  File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/motion_imitation.py", line 256, in evaluate
    si_results, ci_results = self.run_metrics(all_si_preds_ref_file_list, all_ci_preds_ref_file_list, image_size)
  File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/motion_imitation.py", line 192, in run_metrics
    ci_results = self.unpaired_metrics_runner.evaluate(cross_imitation_files, image_size)
  File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/base.py", line 259, in evaluate
    results = self.post_process_results(metric_results)
  File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/base.py", line 286, in post_process_results
    metric_results[key][sub_key] = np.concatenate(feats, axis=0)
ValueError: need at least one array to concatenate

**Comment by StevenLiuWen** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    能截图看一下/workspace/cpfs-data/data/iPER这个目录的目录结构吗
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liuwen
                            
                    
                        
                            
                                    liuwen@shanghaitech.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年2月22日 22:25，FrankMelon1<notifications@github.com> 写道： 






你是运行我们的吗？可以截图发我一下log的错误，尽可能多一点。 发自我的iPhone

…

在 2021年2月22日，下午6:10，FrankMelon1 @.***> 写道： ﻿ 你好，我在更换evaluate.sh的路径后，并且使用最新代码，在运行evaluate.sh时还是会遇到以下问题： running ('ssim', 'psnr', 'lps', 'face-CS', 'OS-CS-reid') metrics with paired samples = 0 running ('OS-freid', 'face-FD', 'is', 'face-CS', 'OS-CS-reid', 'fid') metrics with unpaired samples = 0 我输出了中间all_si_preds_ref_file_list，all_ci_preds_ref_file_list都是空列表 请问这是什么原因呢？期待您的回复！ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.



您好！是运行你们的，下面是全部报错信息，感谢您的回复：

------------ Options -------------

T_pose: False

batch_size: 4

bg_ks: 13

bg_model: ./outputs/checkpoints/deepfillv2/net_epoch_50_id_G.pth

bg_replace: False

body_seg: False

cam_strategy: smooth

checkpoints_dir: ./outputs/checkpoints/

cond_nc: 3

data_dir: /workspace/cpfs-data/data/iPER

dataset_mode: iPER

debug: False

do_saturate_mask: False

face_model: assets/pretrains/sphere20a_20171020.pth

front_warp: False

ft_ks: 3

gen_name: impersonator

gpu_ids: 0

has_detector: True

hmr_model: assets/pretrains/hmr_tf2pt.pth

image_size: 256

images_folder: images_HD

ip:

is_train: False

load_epoch: 0

load_path: ./outputs/checkpoints/lwb_imper/net_epoch_30_id_G.pth

map_name: uv_seg

model: imitator

n_threads_test: 2

name: imper_results

norm_type: instance

only_vis: False

output_dir: /workspace/cpfs-data/impersonator-master/output_evaluate

part_info: assets/pretrains/smpl_part_info.json

port: 31100

post_tune: True

pri_path: ./assets/samples/A_priors/imgs

repeat_num: 6

save_res: False

serial_batches: False

smpl_model: assets/pretrains/smpl_model.pkl

smpls_folder: smpls

src_path:

swap_part: body

test_ids_file: val.txt

tex_size: 3

tgt_path:

time_step: 10

train_ids_file: train.txt

uv_mapping: assets/pretrains/mapper.txt

view_params: R=0,90,0/t=0,0,0

-------------- End ----------------

./outputs/checkpoints/imper_results

Network impersonator was created

Loading net: ./outputs/checkpoints/lwb_imper/net_epoch_30_id_G.pth

Network deepfillv2 was created

Loading net: ./outputs/checkpoints/deepfillv2/net_epoch_50_id_G.pth

0%|                                                                                                 | 0/126 [00:00<?, ?it/s]

Setting up Perceptual loss...

Loading model from: /workspace/cpfs-data/impersonator-master/thirdparty/his_evaluators/his_evaluators/metrics/lpips/weights/v0.1/alex.pth

...Done

[OSNET info] Successfully loaded pretrained weights from "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/data/osnet_ibn_x1_0_imagenet.pth"

** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']

running ('ssim', 'psnr', 'lps', 'face-CS', 'OS-CS-reid') metrics with paired samples = 0

0it [00:00, ?it/s]

/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice.

out=out, **kwargs)

/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars

ret = ret.dtype.type(ret / rcount)

ssim = nan, quality = higher score is better

psnr = nan, quality = higher score is better

lps = nan, quality = lower score is better.

face-CS = nan, quality = higher score is better

OS-CS-reid = nan, quality = higher score is better

running ('OS-freid', 'fid', 'face-CS', 'face-FD', 'is', 'OS-CS-reid') metrics with unpaired samples = 0

0it [00:00, ?it/s]

Traceback (most recent call last):

File "evaluate.py", line 137, in 

device=torch.device("cuda:0")

File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/motion_imitation.py", line 256, in evaluate

si_results, ci_results = self.run_metrics(all_si_preds_ref_file_list, all_ci_preds_ref_file_list, image_size)

File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/motion_imitation.py", line 192, in run_metrics

ci_results = self.unpaired_metrics_runner.evaluate(cross_imitation_files, image_size)

File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/base.py", line 259, in evaluate

results = self.post_process_results(metric_results)

File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/base.py", line 286, in post_process_results

metric_results[key][sub_key] = np.concatenate(feats, axis=0)

ValueError: need at least one array to concatenate



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by FrankMelon1** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 能截图看一下/workspace/cpfs-data/data/iPER这个目录的目录结构吗 liuwen liuwen@shanghaitech.edu.cn 签名由 网易邮箱大师 定制 在2021年2月22日 22:25，FrankMelon1<notifications@github.com> 写道： 你是运行我们的吗？可以截图发我一下log的错误，尽可能多一点。 发自我的iPhone … 在 2021年2月22日，下午6:10，FrankMelon1 @.***> 写道： ﻿ 你好，我在更换evaluate.sh的路径后，并且使用最新代码，在运行evaluate.sh时还是会遇到以下问题： running ('ssim', 'psnr', 'lps', 'face-CS', 'OS-CS-reid') metrics with paired samples = 0 running ('OS-freid', 'face-FD', 'is', 'face-CS', 'OS-CS-reid', 'fid') metrics with unpaired samples = 0 我输出了中间all_si_preds_ref_file_list，all_ci_preds_ref_file_list都是空列表 请问这是什么原因呢？期待您的回复！ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. 您好！是运行你们的，下面是全部报错信息，感谢您的回复：
> […](#)
> ------------ Options ------------- T_pose: False batch_size: 4 bg_ks: 13 bg_model: ./outputs/checkpoints/deepfillv2/net_epoch_50_id_G.pth bg_replace: False body_seg: False cam_strategy: smooth checkpoints_dir: ./outputs/checkpoints/ cond_nc: 3 data_dir: /workspace/cpfs-data/data/iPER dataset_mode: iPER debug: False do_saturate_mask: False face_model: assets/pretrains/sphere20a_20171020.pth front_warp: False ft_ks: 3 gen_name: impersonator gpu_ids: 0 has_detector: True hmr_model: assets/pretrains/hmr_tf2pt.pth image_size: 256 images_folder: images_HD ip: is_train: False load_epoch: 0 load_path: ./outputs/checkpoints/lwb_imper/net_epoch_30_id_G.pth map_name: uv_seg model: imitator n_threads_test: 2 name: imper_results norm_type: instance only_vis: False output_dir: /workspace/cpfs-data/impersonator-master/output_evaluate part_info: assets/pretrains/smpl_part_info.json port: 31100 post_tune: True pri_path: ./assets/samples/A_priors/imgs repeat_num: 6 save_res: False serial_batches: False smpl_model: assets/pretrains/smpl_model.pkl smpls_folder: smpls src_path: swap_part: body test_ids_file: val.txt tex_size: 3 tgt_path: time_step: 10 train_ids_file: train.txt uv_mapping: assets/pretrains/mapper.txt view_params: R=0,90,0/t=0,0,0
> -------------- End ---------------- ./outputs/checkpoints/imper_results Network impersonator was created Loading net: ./outputs/checkpoints/lwb_imper/net_epoch_30_id_G.pth Network deepfillv2 was created Loading net: ./outputs/checkpoints/deepfillv2/net_epoch_50_id_G.pth 0%| | 0/126 [00:00<?, ?it/s] Setting up Perceptual loss... Loading model from: /workspace/cpfs-data/impersonator-master/thirdparty/his_evaluators/his_evaluators/metrics/lpips/weights/v0.1/alex.pth ...Done [OSNET info] Successfully loaded pretrained weights from "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/data/osnet_ibn_x1_0_imagenet.pth" ** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias'] running ('ssim', 'psnr', 'lps', 'face-CS', 'OS-CS-reid') metrics with paired samples = 0 0it [00:00, ?it/s] /anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice. out=out, **kwargs) /anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars ret = ret.dtype.type(ret / rcount) ssim = nan, quality = higher score is better psnr = nan, quality = higher score is better lps = nan, quality = lower score is better. face-CS = nan, quality = higher score is better OS-CS-reid = nan, quality = higher score is better running ('OS-freid', 'fid', 'face-CS', 'face-FD', 'is', 'OS-CS-reid') metrics with unpaired samples = 0 0it [00:00, ?it/s] Traceback (most recent call last): File "evaluate.py", line 137, in device=torch.device("cuda:0") File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/motion_imitation.py", line 256, in evaluate si_results, ci_results = self.run_metrics(all_si_preds_ref_file_list, all_ci_preds_ref_file_list, image_size) File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/motion_imitation.py", line 192, in run_metrics ci_results = self.unpaired_metrics_runner.evaluate(cross_imitation_files, image_size) File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/base.py", line 259, in evaluate results = self.post_process_results(metric_results) File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/base.py", line 286, in post_process_results metric_results[key][sub_key] = np.concatenate(feats, axis=0) ValueError: need at least one array to concatenate —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

目录结构如下：
iPER
   ---images
       ---001
           ---1
                ---1
                     ---0000.jpg
                     ---...
           ---10
                ---1
                     ---000.jpg
                     ---...

   ---iPER_256_video_release
        ---001_1_1.mp4
        ---...

   ---smpls
        ---001
             ---1
                  ---1
                       ---kps.pkl
                       ---pose_shape.pkl

这是某些文件的路径：
/workspace/cpfs-data/data/iPER/images/001/1/1/0010.jpg
/workspace/cpfs-data/data/iPER/images/001/10/1/000.jpg
/workspace/cpfs-data/data/iPER/images/001/33/1/668.jpg

貌似images下文件命名方式不一致？

**Comment by StevenLiuWen** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        你重新按照这个https://github.com/svip-lab/impersonator/blob/master/tools/unzip_iPER.py#L26-L42解压一下。应该命令的问题，用ffmpeg得到的frame_xxxxxx.png，用这个把他们变成跟protocol里面一样的命名。
    
        
            
        
    另外你在evalute.sh加上--images_folder  images因为，默认的这个写的是images_HD，而解压出来保存的是images
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                liuwen
                            
                    
                        
                            
                                    liuwen@shanghaitech.edu.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年2月24日 11:43，FrankMelon1<notifications@github.com> 写道： 






font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 能截图看一下/workspace/cpfs-data/data/iPER这个目录的目录结构吗 liuwen liuwen@shanghaitech.edu.cn 签名由 网易邮箱大师 定制 在2021年2月22日 22:25，FrankMelon1notifications@github.com 写道： 你是运行我们的吗？可以截图发我一下log的错误，尽可能多一点。 发自我的iPhone … 在 2021年2月22日，下午6:10，FrankMelon1 @.***> 写道： ﻿ 你好，我在更换evaluate.sh的路径后，并且使用最新代码，在运行evaluate.sh时还是会遇到以下问题： running ('ssim', 'psnr', 'lps', 'face-CS', 'OS-CS-reid') metrics with paired samples = 0 running ('OS-freid', 'face-FD', 'is', 'face-CS', 'OS-CS-reid', 'fid') metrics with unpaired samples = 0 我输出了中间all_si_preds_ref_file_list，all_ci_preds_ref_file_list都是空列表 请问这是什么原因呢？期待您的回复！ — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe. 您好！是运行你们的，下面是全部报错信息，感谢您的回复：

…

------------ Options ------------- T_pose: False batch_size: 4 bg_ks: 13 bg_model: ./outputs/checkpoints/deepfillv2/net_epoch_50_id_G.pth bg_replace: False body_seg: False cam_strategy: smooth checkpoints_dir: ./outputs/checkpoints/ cond_nc: 3 data_dir: /workspace/cpfs-data/data/iPER dataset_mode: iPER debug: False do_saturate_mask: False face_model: assets/pretrains/sphere20a_20171020.pth front_warp: False ft_ks: 3 gen_name: impersonator gpu_ids: 0 has_detector: True hmr_model: assets/pretrains/hmr_tf2pt.pth image_size: 256 images_folder: images_HD ip: is_train: False load_epoch: 0 load_path: ./outputs/checkpoints/lwb_imper/net_epoch_30_id_G.pth map_name: uv_seg model: imitator n_threads_test: 2 name: imper_results norm_type: instance only_vis: False output_dir: /workspace/cpfs-data/impersonator-master/output_evaluate part_info: assets/pretrains/smpl_part_info.json port: 31100 post_tune: True pri_path: ./assets/samples/A_priors/imgs repeat_num: 6 save_res: False serial_batches: False smpl_model: assets/pretrains/smpl_model.pkl smpls_folder: smpls src_path: swap_part: body test_ids_file: val.txt tex_size: 3 tgt_path: time_step: 10 train_ids_file: train.txt uv_mapping: assets/pretrains/mapper.txt view_params: R=0,90,0/t=0,0,0

-------------- End ---------------- ./outputs/checkpoints/imper_results Network impersonator was created Loading net: ./outputs/checkpoints/lwb_imper/net_epoch_30_id_G.pth Network deepfillv2 was created Loading net: ./outputs/checkpoints/deepfillv2/net_epoch_50_id_G.pth 0%| | 0/126 [00:00<?, ?it/s] Setting up Perceptual loss... Loading model from: /workspace/cpfs-data/impersonator-master/thirdparty/his_evaluators/his_evaluators/metrics/lpips/weights/v0.1/alex.pth ...Done [OSNET info] Successfully loaded pretrained weights from "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/data/osnet_ibn_x1_0_imagenet.pth" ** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias'] running ('ssim', 'psnr', 'lps', 'face-CS', 'OS-CS-reid') metrics with paired samples = 0 0it [00:00, ?it/s] /anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2957: RuntimeWarning: Mean of empty slice. out=out, **kwargs) /anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars ret = ret.dtype.type(ret / rcount) ssim = nan, quality = higher score is better psnr = nan, quality = higher score is better lps = nan, quality = lower score is better. face-CS = nan, quality = higher score is better OS-CS-reid = nan, quality = higher score is better running ('OS-freid', 'fid', 'face-CS', 'face-FD', 'is', 'OS-CS-reid') metrics with unpaired samples = 0 0it [00:00, ?it/s] Traceback (most recent call last): File "evaluate.py", line 137, in device=torch.device("cuda:0") File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/motion_imitation.py", line 256, in evaluate si_results, ci_results = self.run_metrics(all_si_preds_ref_file_list, all_ci_preds_ref_file_list, image_size) File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/motion_imitation.py", line 192, in run_metrics ci_results = self.unpaired_metrics_runner.evaluate(cross_imitation_files, image_size) File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/base.py", line 259, in evaluate results = self.post_process_results(metric_results) File "/workspace/cpfs-data/ICCV2021/impersonator-master/thirdparty/his_evaluators/his_evaluators/evaluators/base.py", line 286, in post_process_results metric_results[key][sub_key] = np.concatenate(feats, axis=0) ValueError: need at least one array to concatenate —You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.



目录结构如下：

iPER

---images

---001

---1

---1

---0000.jpg

---...

---10

---1

---000.jpg

---...

---iPER_256_video_release

---001_1_1.mp4

---...

---smpls

---001

---1

---1

---kps.pkl

---pose_shape.pkl

这是某些文件的路径：

/workspace/cpfs-data/data/iPER/images/001/1/1/0010.jpg

/workspace/cpfs-data/data/iPER/images/001/10/1/000.jpg

/workspace/cpfs-data/data/iPER/images/001/33/1/668.jpg

貌似images下文件命名方式不一致？



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.
